services:
  - type: web
    name: festival-sport-2026
    runtime: docker
    region: frankfurt
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: "10000"
      - key: RUST_LOG
        value: info
